### ISSUE TITLE
New GTK dialog requires xmlstarlet but it has a different name on Ubuntu

### ISSUE THREAD

**Issue by Vexatos** [deterenkelt/Nadeshiko#11]
Setting `dialog='gtk'` in `nadeshiko-mpv.rc.sh` requires the `xml` command from xmlstarlet. On Ubuntu-based distros, however, the command is called `xmlstarlet` instead of `xml`. Symlinking `xml -> xmlstarlet` or setting an alias obviously fixes it.

**Comment by deterenkelt** [comment]
Hm, weird. I’ve changed the dependency to `xmlstarlet` in [v2.2.2](https://github.com/deterenkelt/Nadeshiko/releases/latest).
