### ISSUE TITLE
Per-pass progress

### ISSUE THREAD

**Issue by RX14** [deterenkelt/Nadeshiko#18]
Perhaps it's possible to make ffmpeg print only the small one-line progress line, or to isolate it, then show that to the user when running a pass to give some idea on time remaining.

Not important, but would be nice if it's easy.

**Comment by deterenkelt** [comment]
Not that easy, but easier than I imagined it to be. Progress bar for ffmpeg is implemented in [Nadeshiko-2.9](https://github.com/deterenkelt/Nadeshiko/releases/tag/v2.9).

**Comment by RX14** [comment]
holy fucking shit you're amazing i love you

**Comment by deterenkelt** [comment]
K-k-keep it professional!

![ReinForce  Love Lab - 04 (BDRip 1920x1080 x264 FLAC) 00:13:05 785](https://user-images.githubusercontent.com/2245254/59446365-0b2fa600-8e0a-11e9-89b3-d88ace776fe0.jpg)
