### ISSUE TITLE
Allow J (cycle subtitles) and # (cycle audio) to affect nadeshiko-mpv

### ISSUE THREAD

**Issue by Vexatos** [deterenkelt/Nadeshiko#9]
### What Nadeshiko was supposed to do

Cycling to `no` using J or # in mpv to disable subtitles or audio should make nadeshiko-mpv also turn off subs and audio, respectively.

### What happened

It doesn't. It seems to just use the previously selected one.

### Steps for developer-san to reproduce the problem

* Open video with audio and/or subtitles
* run `nadeshiko-mpv.sh`
* use J or # to cycle either of then to `no`
* run `nadeshiko-mpv.sh`
* See that subtitles and audio are still a thing in the preview, and also in the resulting baked video.

### Logs

Nothing to see here, but it shows
```
mute=no
sub_visibility=yes
```
when it definitely shouldn't.

### Software versions

```
ffmpeg version 4.0.2-1~18.04.york0 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
configuration: --prefix=/usr --extra-version='1~18.04.york0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      56. 14.100 / 56. 14.100
libavcodec     58. 18.100 / 58. 18.100
libavformat    58. 12.100 / 58. 12.100
libavdevice    58.  3.100 / 58.  3.100
libavfilter     7. 16.100 /  7. 16.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  1.100 /  5.  1.100
libswresample   3.  1.100 /  3.  1.100
libpostproc    55.  1.100 / 55.  1.100
```

**Comment by deterenkelt** [comment]
<kbd>j</kbd> only switches tracks, the key that switches sub-visibility property is <kbd>v</kbd>.

Actually, “Subtitles: no” either shouldn’t be present, or should invisibly switch sub-visibility on/off, when the selection jumps from “no” to subtitles and back.

It’s a specific of mpv behaviour, there’s nothing to be done here. You may try to report it as a bug, but there would be little hope, that they combine J and V actions.
